# Language for messages (e.g., 'en' for English, 'ru' for Russian)
# If you want to help translate PlayerManager into your language Join our Discord https://discord.gg/72mzBTckKC and check the #translations channel

# Plugin info
config-version: "1.1.0"
language: "en"

# Feature toggles
features:
  player-teleportation: true
  inventory-inspection: true
  ender-chest-inspection: true
  punishment-system: true
  player-info-actions: true
  ip-search: true

# === Player Data Cleanup ===
# Deleting data of inactive players / Удаление данных неактивных игроков
max-inactivity-days: 30
# Check interval (in hours) / Интервал проверки (в часах)
cleanup-interval-hours: 24